### ISSUE TITLE
"Open live view" button not visible if field have "%" char.

### ISSUE THREAD

**Issue by Miro0** [mattmilburn/strapi-plugin-preview-button#124]
I noticed following issue - tested with current version `2.2.1`.

Minimum steps to reproduce:
1. Defined minimum content type:
```
{
  "kind": "collectionType",
  "collectionName": "tests",
  "info": {
    "singularName": "test",
    "pluralName": "tests",
    "displayName": "Test",
    "description": ""
  },
  "attributes": {
    "Test": {
      "type": "string"
    }
  }
}
```
2. Added plugin config:
```
'preview-button': {
    config: {
      contentTypes: [
        {
          uid: 'api::test.test',
          published: {
            url: `http://localhost:3000/{locale}/test/{id}`,
            openTarget: '_blank',
          },
        }
      ],
    },
  },
```
3. Content:
- If there's no `%` char in field - `Open live view` exists:
![image](https://github.com/mattmilburn/strapi-plugin-preview-button/assets/13290580/2875a928-8112-478c-83d8-bec5d4c5717f)
- If there's `%` char in field - `Open live view` do not exists:
![image](https://github.com/mattmilburn/strapi-plugin-preview-button/assets/13290580/5d589ed7-e37e-4699-bbf2-2c38b091885a)

There is also additional error in browser console:
```
main.c2325b99.js:2185 Uncaught (in promise) URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at main.c2325b99.js:2185:1707
    at Array.reduce (<anonymous>)
    at P (main.c2325b99.js:2185:1636)
    at z (main.c2325b99.js:2185:1952)
    at main.c2325b99.js:2185:3391
```
thrown in `main.c2325b99.js:2185`

**Comment by mattmilburn** [comment]
Hi @Miro0 This was actually fixed in 2.2.1 🤔  Have you tried removing `yarn.lock` or `node_modules` and reinstalling with `yarn`? That `encodeURIcomponent(decodeURIComponent(value))` code was definitely replaced in the latest version.

**Comment by mattmilburn** [comment]
Closing due to inactivity
